#!/bin/bash -e
python -m coverage run $(type -p trial) txgraylog
coverage report --include='*/txgraylog/*' --omit='*/txgraylog/test/*'
coverage html -d txgraylog/test/reports --include='*/txgraylog/*' --omit='*/txgraylog/test/*'
